/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { StateObj } from "./store/todo-Store";
export namespace Components {
    interface MyContainer {
    }
    interface MyInput {
    }
    interface MyListOfTodos {
        "textInput": HTMLInputElement;
        "todoListProp": StateObj;
    }
}
declare global {
    interface HTMLMyContainerElement extends Components.MyContainer, HTMLStencilElement {
    }
    var HTMLMyContainerElement: {
        prototype: HTMLMyContainerElement;
        new (): HTMLMyContainerElement;
    };
    interface HTMLMyInputElement extends Components.MyInput, HTMLStencilElement {
    }
    var HTMLMyInputElement: {
        prototype: HTMLMyInputElement;
        new (): HTMLMyInputElement;
    };
    interface HTMLMyListOfTodosElement extends Components.MyListOfTodos, HTMLStencilElement {
    }
    var HTMLMyListOfTodosElement: {
        prototype: HTMLMyListOfTodosElement;
        new (): HTMLMyListOfTodosElement;
    };
    interface HTMLElementTagNameMap {
        "my-container": HTMLMyContainerElement;
        "my-input": HTMLMyInputElement;
        "my-list-of-todos": HTMLMyListOfTodosElement;
    }
}
declare namespace LocalJSX {
    interface MyContainer {
    }
    interface MyInput {
    }
    interface MyListOfTodos {
        "textInput"?: HTMLInputElement;
        "todoListProp"?: StateObj;
    }
    interface IntrinsicElements {
        "my-container": MyContainer;
        "my-input": MyInput;
        "my-list-of-todos": MyListOfTodos;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-container": LocalJSX.MyContainer & JSXBase.HTMLAttributes<HTMLMyContainerElement>;
            "my-input": LocalJSX.MyInput & JSXBase.HTMLAttributes<HTMLMyInputElement>;
            "my-list-of-todos": LocalJSX.MyListOfTodos & JSXBase.HTMLAttributes<HTMLMyListOfTodosElement>;
        }
    }
}
